# Generated by Django 2.1.4 on 2018-12-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
    ]
